### ISSUE TITLE
stale_package_check fails to find package functions

### ISSUE THREAD

**Issue by neilhatfield** [MichaelChirico/funchir#16]
When a function is called with an explicit reference to the package to avoid namespace issues, (e.g., `matrixcalc::matrix.power`) `stale_package_check` will return the message "\*\*No exported functions matched from matrixcalc\*\*". If you drop the package reference, then the check returns the expected output ("Functions matched from package...").

As far as I can tell, this happens with any package, not just the example of matrixcalc.

**Comment by MichaelChirico** [comment]
IIRC I'm taking the stance that `library()` is not required for packages only used by namespace (the script should work just the same if you remove the `library(matrixcalc)` call).

I think by now, this function should be superseded by `lintr::unused_import_linter()` -- could you try that out & see if it's more useful? That package is also getting a lot more "foot traffic" so I imagine it's more robust :)

**Comment by MichaelChirico** [comment]
All development will be in {lintr} going forward, thanks!
